steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/invensir-12312/authentication', '.']
  dir: 'authentication'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/invensir-12312/authentication']
  dir: 'authentication'
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 
    'deploy', 
    'auth-staging', 
    '--image', 
    'gcr.io/invensir-12312/authentication', 
    '--region', 
    'asia-southeast2',
    '--allow-unauthenticated'
  ]
  dir: 'authentication'
images:
- gcr.io/invensir-12312/authentication